### ISSUE TITLE
No information regarding the image corresponding to a BT score value.

### ISSUE THREAD

**Issue by b-amb** [yia-yuese/SAUD-Dataset#1]
In the sub_bt_scores.mat, there is a single score value. Can you please provide the corresponding image name for each BT score value?

**Comment by yia-yuese** [comment]
Thank you very much for your suggestions to improve our work. We are working on it and will upload it soon.

**Comment by yia-yuese** [comment]
> In the sub_bt_scores.mat, there is a single score value. Can you please provide the corresponding image name for each BT score value?

Thank you very much for your suggestions to improve our work. We are working on it and will upload it soon.

**Comment by b-amb** [comment]
Thank you for updating.
